import React from "react";
import "./Form.css"; // ek css file banayenge

export default function LeadMasterForm() {
  return (
    <div className="form-wrapper">
      <h2 className="form-title">Add New Lead</h2>
      <form className="grid-form">
        {/* Row 1 */}
        <div className="form-group">
          <label>Start Date:</label>
          <input type="date" />
        </div>
        <div className="form-group">
          <label>End Date:</label>
          <input type="date" />
        </div>
        <div className="form-group">
          <label>Lead Entered By:</label>
          <select>
            <option>Loading...</option>
          </select>
        </div>
        <div className="form-group">
          <label>Lead Generated By:</label>
          <select>
            <option>Loading...</option>
          </select>
        </div>

        {/* Row 2 */}
        <div className="form-group">
          <label>Title:</label>
          <select>
            <option>Select...</option>
            <option>Mr.</option>
            <option>Mrs.</option>
            <option>Ms.</option>
            <option>Miss.</option>
            <option>M/S</option>
          </select>
        </div>
        <div className="form-group">
          <label>Client Name:</label>
          <input type="text" />
        </div>
        <div className="form-group">
          <label>Mobile:</label>
          <input type="text" />
        </div>
        <div className="form-group">
          <label>Email:</label>
          <input type="email" />
        </div>

        {/* Row 3 */}
        <div className="form-group">
          <label>Product Type:</label>
          <select>
            <option>Loading...</option>
          </select>
        </div>
        <div className="form-group">
          <label>Registration No.:</label>
          <input type="text" />
        </div>
        <div className="form-group">
          <label>Date of Birth:</label>
          <input type="date" />
        </div>
        <div className="form-group">
          <label>Family Size:</label>
          <select>
            <option>Loading...</option>
          </select>
        </div>

        {/* Row 4 */}
        <div className="form-group">
          <label>Nominee Name:</label>
          <input type="text" />
        </div>
        <div className="form-group">
          <label>Relationship:</label>
          <select>
            <option>Select Relationship</option>
            <option>Mother</option>
            <option>Father</option>
            <option>Brother</option>
            <option>Sister</option>
            <option>Spouse</option>
            <option>Child</option>
            <option>Friend</option>
            <option>Other</option>
          </select>
        </div>
        <div className="form-group">
          <label>Nominee DOB:</label>
          <input type="date" />
        </div>
        <div className="form-group">
          <label>Annual Income (in INR):</label>
          <select>
            <option>Select Income Slab</option>
            <option>0 - 5 Lakh</option>
            <option>5 - 10 Lakh</option>
            <option>10 - 15 Lakh</option>
            <option>15 - 25 Lakh</option>
            <option>25 - 35 Lakh</option>
            <option>35 - 50 Lakh</option>
            <option>50 - 75 Lakh</option>
            <option>Above 75 Lakh</option>
          </select>
        </div>

        {/* Row 5 */}
        <div className="form-group">
          <label>Remarks:</label>
          <input type="text" />
        </div>
        <div className="form-group">
          <label>Address 1:</label>
          <input type="text" />
        </div>
        <div className="form-group">
          <label>Address 2:</label>
          <input type="text" />
        </div>
        <div className="form-group">
          <label>Pin Code:</label>
          <input type="text" />
        </div>
      </form>

      <div className="btn-row">
        <button type="submit" className="btn primary">
          Submit
        </button>
        <button type="button" className="btn secondary">
          Search
        </button>
        <button type="reset" className="btn danger">
          Reset
        </button>
      </div>
    </div>
  );
}
