import React from "react";
import "./Form.css";

export default function PartnerPayoutProcess() {
  return (
    <div className="form-wrapper">
      <h2 className="form-title">Partner Payout Process</h2>

      {/* Filter/Search Section */}
      <form className="grid-form">
        <div className="form-group">
          <label>Lead Generated By:</label>
          <select>
            <option>-- Select --</option>
            <option>Agent A</option>
            <option>Agent B</option>
          </select>
        </div>
        <div className="form-group">
          <label>Issuance Month:</label>
          <input type="month" />
        </div>
        <div className="form-group">
          <label>Login Month:</label>
          <input type="month" />
        </div>
        <div className="form-group">
          <label>Status:</label>
          <select>
            <option>-- Select --</option>
            <option>Pending</option>
            <option>Approved</option>
            <option>Rejected</option>
          </select>
        </div>
      </form>

      <div className="btn-row" style={{ marginTop: "15px" }}>
        <button type="button" className="btn primary">
          Search
        </button>
        <button type="reset" className="btn danger">
          Reset
        </button>
      </div>

      {/* Table Section */}
      <div style={{ marginTop: "25px", overflowX: "auto" }}>
        <table
          style={{
            width: "100%",
            borderCollapse: "collapse",
            marginTop: "10px",
          }}
        >
          <thead>
            <tr style={{ background: "#0d6efd", color: "#fff" }}>
              <th style={thStyle}>Lead Generated By</th>
              <th style={thStyle}>Issuance Month</th>
              <th style={thStyle}>Partner Gross Amount</th>
              <th style={thStyle}>TDS</th>
              <th style={thStyle}>Partner Net Amount</th>
              <th style={thStyle}>Status</th>
              <th style={thStyle}>Action</th>
            </tr>
          </thead>
          <tbody>
            {Array.from({ length: 3 }).map((_, idx) => (
              <tr key={idx}>
                <td style={tdStyle}>Agent {idx + 1}</td>
                <td style={tdStyle}>09/2025</td>
                <td style={tdStyle}>₹20,000</td>
                <td style={tdStyle}>₹2,000</td>
                <td style={tdStyle}>₹18,000</td>
                <td style={tdStyle}>Pending</td>
                <td style={tdStyle}>
                  <button className="btn small primary">Process</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

const thStyle = {
  padding: "10px",
  border: "1px solid #ddd",
  fontSize: "14px",
  textAlign: "center",
};

const tdStyle = {
  padding: "8px",
  border: "1px solid #ddd",
  textAlign: "center",
};
