import React from "react";
import "./Form.css";

export default function PolicyMaster() {
  return (
    <div className="form-wrapper">
      <h2 className="form-title">Enter Policy Details</h2>

      {/* Filter/Search Section */}
      <form className="grid-form">
        <div className="form-group">
          <label>Search Lead ID or Client Name:</label>
          <input type="text" placeholder="CLIENT NAME" />
        </div>
        <div className="form-group">
          <label>Lead Generated By:</label>
          <select>
            <option>Select...</option>
            <option>Agent</option>
            <option>Broker</option>
            <option>Referral</option>
          </select>
        </div>
        <div className="form-group">
          <label>Product Type:</label>
          <select>
            <option>Select...</option>
            <option>Motor</option>
            <option>Life</option>
            <option>Health</option>
            <option>SME</option>
          </select>
        </div>
        <div className="form-group">
          <label>Proposal Status:</label>
          <select>
            <option>Select...</option>
            <option>Pending</option>
            <option>Approved</option>
            <option>Rejected</option>
          </select>
        </div>

        <div className="form-group">
          <label>Insurance Company Name:</label>
          <select>
            <option>Select...</option>
            <option>HDFC Life</option>
            <option>ICICI Lombard</option>
            <option>SBI Life</option>
            <option>Bajaj Allianz</option>
          </select>
        </div>
        <div className="form-group">
          <label>Start Date:</label>
          <input type="date" />
        </div>
        <div className="form-group">
          <label>End Date:</label>
          <input type="date" />
        </div>
      </form>

      <div className="btn-row" style={{ marginTop: "15px" }}>
        <button type="button" className="btn primary">
          Search
        </button>
        <button type="reset" className="btn danger">
          Reset Filters
        </button>
      </div>

      {/* Table Section */}
      <div style={{ marginTop: "25px", overflowX: "auto" }}>
        <table
          style={{
            width: "100%",
            borderCollapse: "collapse",
            marginTop: "10px",
          }}
        >
          <thead>
            <tr style={{ background: "#0d6efd", color: "#fff" }}>
              <th style={thStyle}>Login ID</th>
              <th style={thStyle}>Client Name</th>
              <th style={thStyle}>Lead Generated By</th>
              <th style={thStyle}>Product Type</th>
              <th style={thStyle}>Insurance Company Name</th>
              <th style={thStyle}>Login Date</th>
              <th style={thStyle}>Proposal No.</th>
              <th style={thStyle}>Proposal Status</th>
              <th style={thStyle}>Action</th>
            </tr>
          </thead>
          <tbody>
            {/* Dummy Rows */}
            {Array.from({ length: 3 }).map((_, idx) => (
              <tr key={idx}>
                <td style={tdStyle}>LID00{idx + 1}</td>
                <td style={tdStyle}>Client {idx + 1}</td>
                <td style={tdStyle}>Agent</td>
                <td style={tdStyle}>Life</td>
                <td style={tdStyle}>HDFC Life</td>
                <td style={tdStyle}>01/10/2025</td>
                <td style={tdStyle}>PN00{idx + 1}</td>
                <td style={tdStyle}>Pending</td>
                <td style={tdStyle}>
                  <button className="btn small">View</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

const thStyle = {
  padding: "10px",
  border: "1px solid #ddd",
  fontSize: "14px",
  textAlign: "center",
};

const tdStyle = {
  padding: "8px",
  border: "1px solid #ddd",
  textAlign: "center",
};
